// <auto-generated />
using CPRG102.Final.Roland.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CPRG102.Final.Roland.Data.Migrations
{
    [DbContext(typeof(AssetContext))]
    [Migration("20201115063349_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CPRG102.Final.Roland.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("ModelId");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("CPRG102.Final.Roland.Domain.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssetType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tablet"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mobile Phone"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Desk Phone"
                        });
                });

            modelBuilder.Entity("CPRG102.Final.Roland.Domain.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Acer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "LG"
                        },
                        new
                        {
                            Id = 5,
                            Name = "HP"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Avaya"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Polycom"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cisco"
                        });
                });

            modelBuilder.Entity("CPRG102.Final.Roland.Domain.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Model");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManufacturerId = 1,
                            Name = "iPad mini"
                        },
                        new
                        {
                            Id = 2,
                            ManufacturerId = 1,
                            Name = "iPad air"
                        },
                        new
                        {
                            Id = 3,
                            ManufacturerId = 1,
                            Name = "iPhone 5"
                        },
                        new
                        {
                            Id = 4,
                            ManufacturerId = 1,
                            Name = "iPhone 6"
                        },
                        new
                        {
                            Id = 5,
                            ManufacturerId = 2,
                            Name = "Galaxy Tab3"
                        },
                        new
                        {
                            Id = 6,
                            ManufacturerId = 2,
                            Name = "Galaxy S4"
                        },
                        new
                        {
                            Id = 7,
                            ManufacturerId = 2,
                            Name = "Galaxy S5"
                        },
                        new
                        {
                            Id = 8,
                            ManufacturerId = 2,
                            Name = "Galaxy Note5"
                        },
                        new
                        {
                            Id = 9,
                            ManufacturerId = 3,
                            Name = "S200"
                        },
                        new
                        {
                            Id = 10,
                            ManufacturerId = 3,
                            Name = "STQ414"
                        },
                        new
                        {
                            Id = 11,
                            ManufacturerId = 4,
                            Name = "22MP"
                        },
                        new
                        {
                            Id = 12,
                            ManufacturerId = 5,
                            Name = "Pavilion"
                        },
                        new
                        {
                            Id = 13,
                            ManufacturerId = 6,
                            Name = "9612G"
                        },
                        new
                        {
                            Id = 14,
                            ManufacturerId = 7,
                            Name = "SoundPoint 331"
                        },
                        new
                        {
                            Id = 15,
                            ManufacturerId = 8,
                            Name = "SPA525G2"
                        });
                });

            modelBuilder.Entity("CPRG102.Final.Roland.Domain.Asset", b =>
                {
                    b.HasOne("CPRG102.Final.Roland.Domain.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPRG102.Final.Roland.Domain.Manufacturer", "Manufacturer")
                        .WithMany("Assets")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CPRG102.Final.Roland.Domain.Model", "Model")
                        .WithMany("Assets")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");

                    b.Navigation("Manufacturer");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("CPRG102.Final.Roland.Domain.Model", b =>
                {
                    b.HasOne("CPRG102.Final.Roland.Domain.Manufacturer", null)
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CPRG102.Final.Roland.Domain.AssetType", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("CPRG102.Final.Roland.Domain.Manufacturer", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Models");
                });

            modelBuilder.Entity("CPRG102.Final.Roland.Domain.Model", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
